export const QA = [
  {id:1,cat:'İmmünoloji',q:'CVID, XLA ve HIV birlikte ise seyir?',a:'XLA: B hücresi yok → antikor yok; HIV: CD4 T düşer; CVID: antikor az. Birlikte hücresel+humoral zayıf → sık sinopulmoner inf., diyare, fırsatçı etken; aşı yanıtı zayıf.'},
  {id:2,cat:'İmmünoloji',q:'Selektif IgA eksikliğinde salgısal IgA?',a:'Serum IgA düşük/yok; mukozal salgısal IgA da düşer (kompansatuvar IgM artabilir).'},
  {id:3,cat:'İmmünoloji',q:'Downey hücreleri nerede?',a:'EBV enf. (infeksiyöz mononükleoz) sırasında görülen atipik reaktif T-lenfositler.'},
  {id:4,cat:'İmmünoloji',q:'0 kan grubunda doğal antikorlar?',a:'0 grubu serumunda doğal anti-A ve anti-B IgM antikorlar vardır; RBC yüzeyinde A/B antijeni yoktur.'},
  {id:5,cat:'İmmünoloji',q:'Chediak–Higashi’de trombosit?',a:'Sayı normal/az; dev granüllerle fonksiyon kusuru; kanama zamanı uzayabilir.'},
  {id:6,cat:'İmmünoloji',q:'Kontrast madde anafilaktoid?',a:'IgE’siz mast hücre/bazofil degranülasyonu ve/veya kompleman aktivasyonu → psödoalerjik reaksiyon.'},
  {id:7,cat:'İmmünoloji',q:'AB0 uyumsuzluğu?',a:'Alıcının doğal IgM antikorları vericinin RBC antijenine bağlanır → komplemanla intravasküler hemoliz.'},
  {id:20,cat:'Nöroloji',q:'ALS vs SMA?',a:'ALS: ÜMN+AMN birlikte, duyu korunur. SMA: yalnız AMN; hiporefleksi, fasikülasyon; ÜMN bulgusu yok.'},
  {id:21,cat:'Nöroloji',q:'ALS’de hem hipo hem hiper refleks?',a:'Evet; ÜMN lezyon hiperrefleksi, AMN hasarı hiporefleksi yapar; aynı hastada birlikte olabilir.'},
  {id:22,cat:'Nöroloji',q:'Dravet özeti?',a:'İlk yıl hemikonvulsif/uzamış febril nöbetler; SCN1A; ateş tetikler; sodyum kanal blokerlerinden kaçın.'},
  {id:25,cat:'Nöroloji',q:'Myasteniada DTR?',a:'Genellikle normal; ağır güçsüzlükte düşük görünebilir ama refleks arkı sağlamdır.'},
  {id:27,cat:'Nöroloji',q:'Konus medullaris DTR neden artar?',a:'Üst segment traktus etkilenimi ÜMN bulgularını ekleyebilir; karma görünümler olur.'},
  {id:40,cat:'Pediatri',q:'Mekonyum ileus grafi?',a:'Sabun köpüğü görünümü, distal ince barsakta küçük kabarcıklı görünüm; CF ile ilişkili.'},
  {id:80,cat:'Yoğun Bakım',q:'O2 sat vs PaO2?',a:'Sat: Hb doluluk yüzdesi; PaO2: çözünmüş O2 basıncı. Eğri nedeniyle doğrusal değil.'},
  {id:81,cat:'Yoğun Bakım',q:'Hiperkalemi ve β-agonist/epi/süksinilkolin?',a:'β2-agonist K’yi hücre içine alır (↓). Süksinilkolin K salınımını ↑ (yanık/nörolojik hasar/immobilite’de tehlikeli).'},
  {id:100,cat:'Endokrinoloji',q:'Eksojen T3/T4 vs iyot, Tg?',a:'Eksojen hormon → Tg düşük. İyotla tetiklenmiş hipertiroidide Tg normal/yüksek olabilir.'},
  {id:101,cat:'Endokrinoloji',q:'TSH ve sıcak/soğuk nodül?',a:'TSH düşük+sıcak nodül: malignite düşük. TSH normal/yüksek+soğuk nodül: risk yüksek.'},
  {id:102,cat:'Nefroloji',q:'Gordon’da kalsiyüri?',a:'NCC ↑ → tiazidin tersi; TRPV5 üzerinden Ca girişi azalır → kalsiyüri artabilir.'},
  {id:120,cat:'Hematoloji',q:'Poikilositoz?',a:'Eritrosit şekil anormalliklerinin genel adıdır.'},
  {id:122,cat:'Hematoloji',q:'Auer çubuğu?',a:'MPO pozitif çubuk granüller; AML/özellikle APL.'},
  {id:140,cat:'Onkoloji',q:'RCC paraneoplastik?',a:'EPO↑ polisitemi, PTHrP hiperkalsemi, renin/ACTH; nadir hipoglisemi (IGF-2).'},
  {id:141,cat:'Onkoloji',q:'İnflamatuar meme ca tanı?',a:'Klinik+dermal lenfatik invazyon biyopsisi; neoadjuvan KT → cerrahi → RT.'},
  {id:160,cat:'Nefroloji',q:'Subepitelyal hörgüç?',a:'APSGN’de tipik; membranözde ise diffüz subepitelyal birikim ve spike.'},
  {id:200,cat:'Gastro',q:'Alkol/diyet ülser?',a:'Ana neden H. pylori/NSAİİ; alkol/diyet irritan, doğrudan ana neden değil.'},
  {id:220,cat:'Psikiyatri',q:'REM UDB vs uyku terörü?',a:'REM UDB: REM, rüya içeriği hatırlanır. Uyku terörü: NREM3, yoğun otonomi, amnezi.'},
  {id:240,cat:'Radyoloji',q:'ARDS grafi?',a:'Bilateral yaygın infiltratlar, kalp boyutu normal, kardiyojenik ödem bulgusu yok.'}
]
